### ISSUE TITLE
Matches "0.0.0"

### ISSUE THREAD

**Issue by carldunham** [sindresorhus/semver-regex#13]
It's actually not clear if 0.0.0 is a valid version number under [semver 2.0](https://semver.org/), but it seems wrong. The FAQ recommends starting development at 0.1.0, but that's not it in the spec, _per se_.

**Comment by sindresorhus** [comment]
`0.0.0` is a valid version. I often use it during initial development. https://runkit.com/sindresorhus/5ab2acf225eebc001213ead7

**Comment by carldunham** [comment]
Yeah, doing some more reading, and found things like [this](https://github.com/semver/semver/issues/363), which support the argument. Closing.

**Comment by M-Fabian** [comment]
So will the FAQ be updated? I also favor starting with 0.0.0 because then the major 0 space is equal to the major M space with M >= 1.
