### ISSUE TITLE
Backport the ReDoS fix in v2.0.0

### ISSUE THREAD

**Issue by XhmikosR** [sindresorhus/semver-regex#22]
Hey, @sindresorhus. I know you might not support v2.0.0, but there are so many packages that are still using it: https://www.npmjs.com/package/semver-regex?activeTab=versions

```
2.0.0
1,955,620
```

Would it be possible to backport the fix for 2.x too?

Thanks!

PS. the `latest` npm tag points to v3.1.3, not sure if that's intentional.

**Comment by sindresorhus** [comment]
I don't plan to backport to v2. v2 is a very old release. I generally only backport one release back.

**Comment by sindresorhus** [comment]
> but there are so many packages that are still using it:

You don't know that. It could be a single popular dependency that never updated.

**Comment by sindresorhus** [comment]
> PS. the latest npm tag points to v3.1.3, not sure if that's intentional.

Thanks for letting me know. Fixed.

**Comment by XhmikosR** [comment]
The issue for me is this dep chain: bin-wrapper -> find-versions -> semver-regex.

I'm only judging by the numbers, and the numbers are big.

**Comment by sindresorhus** [comment]
The "vulnerability" does not apply to `bin-wrapper`.

**Comment by sindresorhus** [comment]
https://github.com/npm/rfcs/pull/422 would solve this.

**Comment by XhmikosR** [comment]
Yup, agreed, thanks for the info!

**Comment by lorand-horvath** [comment]
@sindresorhus I have this dep chain: bin-wrapper > bin-version-check > bin-version > find-versions > semver-regex which audits as vulnerable to ReDoS because it depends on the unpatched semver-regex 2.0.0
Is there something I can do to fix this? It's driving me crazy.
