### ISSUE TITLE
`v` prefix is not part of semver

### ISSUE THREAD

**Issue by jelhan** [sindresorhus/semver-regex#7]
`'v1.0.0'.match(semverRegex())` returns `['v1.0.0']` but should be `['1.0.0']`.

**Comment by sindresorhus** [comment]
[`node-semver`](https://github.com/npm/node-semver) handles the `v` fine. I don't really see a good way around this, as if you look at the regex itself, you see that it needs to not match `foo1.0.0`, but match `v1.0.0` and `1.0.0`. PR welcome if you have a solution for this.

**Comment by jelhan** [comment]
Following spec 2.0.0 I didn't see why a `v` prefix should be treated differently than any other prefix. I guess `semverRegex.test('foo1.0.0')` should be `true` if `semverRegex.test('v1.0.0')` returns `true`. In both cases `.match(semverRegex())` should return `['1.0.0']`.

**Comment by sindresorhus** [comment]
`v` is a common convention for indicating something is a version. You can see it in most git tags on GitHub.

- https://github.com/nodejs/node/tags
- https://github.com/facebook/react/tags

-

I do agree the correct way would be to return the matched version without the `v` prefix, but the prefix is so common we can't ignore versions with it, and `foo1.0.0` should definitely not be matched. Happy to consider a solution that satisfies these requirements :)

**Comment by jelhan** [comment]
I have taken another path for my feature I needed this. Haven't any idea myself how this one could be handled just by RegExp.

**Comment by sindresorhus** [comment]
@jelhan I don't know what you need it for, but you might find [`find-versions`](https://github.com/sindresorhus/find-versions) useful.

**Comment by piranna** [comment]
`semver` package [clean() method](https://github.com/npm/node-semver/blob/d21444a0658224b152ce54965d02dbe0856afb84/semver.js#L265-L268) remove all equal and `v` characters on its regexp.
