### ISSUE TITLE
Docker Version Question

### ISSUE THREAD

**Issue by nicky-lenaers** [sindresorhus/semver-regex#9]
Hi,

I'm using this plugin for e.g. detecting the current installment version of `docker`. When running `docker --version`, I get this:

```sh
Docker version 17.03.1-ce-rc1, build 3476dbf
```

It seems the part of `17.03.1` is a semantic version, but using `semverRegex().exec(/*...*/)` it returns `null`.

Should be above version of `docker` be considered semantic? If so, it is possible to include this in the plugin?

Many thanks!

**Comment by sindresorhus** [comment]
It's not valid semver. Note the `0` before the `3`.

**Comment by sindresorhus** [comment]
If you need to extract the version, check out: https://github.com/sindresorhus/find-versions

**Comment by nicky-lenaers** [comment]
I see, thanks for the response. I've just tested `find-versions` and the `loose` option does what I'm after. Thanks!
